schedule training on user-provided node pool
odahu/odahu-flow pull request #323
Opened 2020-08-28 10:46 UTC by keshamin

Closes #243.

2020-09-08 07:01 UTC, vlad-tokarev commented
Let's generate typescript client too, (using makefile)

2020-09-08 07:05 UTC, vlad-tokarev requested changes
Let's generate typescript client too, (using makefile)

2020-09-08 11:38 UTC, keshamin commented
> Let's generate typescript client too, (using makefile)

Done: odahu/odahu-ui#36

2020-09-08 16:04 UTC, maxkochubey approved these changes

2020-09-09 09:40 UTC, vlad-tokarev approved these changes

2020-09-09 12:07 UTC, merged