ModelRoute should be stored in API Server (database)
odahu/odahu-flow pull request #439
Opened 2020-11-27 07:46 UTC by vlad-tokarev

- [x] ModelRoute should be stored in database and synced with kubernetes by ODAHU syncer (controller)
- [x] Default ModelRoute that directs 100% traffic to model should be managed by API server (not odahu kubernetes operator)
- [x] Default ModelRoute is not available for updating or deleting by user (system entity)
- [x] Add integration tests
- [x] Add API for ModelRoute repository to check whether the route is default

2020-11-29 12:28 UTC, keshamin commented on packages/operator/pkg/apis/deployment/model_route.go
> +	// One ModelDeployment as exactly one default route that give 100% traffic to the model
```suggestion
	// One ModelDeployment has exactly one default Route that gives 100% traffic to the model
```

2020-11-29 12:28 UTC, keshamin commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment.go
> +func (mdc *ModelDeploymentController) getDefaultRoute(c *gin.Context) {
It is, of course, a matter of taste, but what do you think of implementing this via something like `GET /api/v1/model/route?deployment_id=123&default=true`? Because it is generally just filtering which perfectly fits to classic REST design.

2020-11-29 12:29 UTC, keshamin approved these changes

2020-11-29 17:09 UTC, vlad-tokarev commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment.go
> +func (mdc *ModelDeploymentController) getDefaultRoute(c *gin.Context) {
It makes sense, but in this way, we have got a collection of model routes with length from 0 to 1, I think separate API also makes sense. We could add filtering in LIST /api/v1/model/route in future

2020-11-30 11:06 UTC, BPylypenko requested changes

2020-11-30 11:06 UTC, BPylypenko commented on packages/operator/docs/swagger.yaml
> +          One ModelDeployment as exactly one default route that give 100% traffic to the model
```suggestion
          Default routes cannot be deleted by user. They are managed by system
          One ModelDeployment has exactly one default Route that gives 100% traffic to the model
```
I suppose it should be in this way: https://github.com/odahu/odahu-flow/pull/439/files?file-filters%5B%5D=.go&file-filters%5B%5D=.json&file-filters%5B%5D=.mod&file-filters%5B%5D=.py&file-filters%5B%5D=.robot&file-filters%5B%5D=.sql&file-filters%5B%5D=.yaml&hide-deleted-files=true#diff-3ea98d649ec32d490f257bdd6fd340869105d6be75c6855f5c1696bbd8e08cedR27

2020-11-30 11:06 UTC, BPylypenko commented on packages/operator/docs/swagger.yaml
> +        description: Node pools to run deployments on
```suggestion
        description: Node pools to run deployments
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/operator/docs/swagger.json
> +                    "description": "Default routes cannot be deleted by  They are managed by system\nOne ModelDeployment as exactly one default route that give 100% traffic to the model",
```suggestion
                    "description": "Default routes cannot be deleted by user. They are managed by system\nOne ModelDeployment has exactly one default Route that gives 100% traffic to the model",
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/operator/docs/docs.go
> +                    "description": "Default routes cannot be deleted by  They are managed by system\nOne ModelDeployment as exactly one default route that give 100% traffic to the model",
```suggestion
                    "description": "Default routes cannot be deleted by user. They are managed by system\nOne ModelDeployment has exactly one default Route that gives 100% traffic to the model",
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/sdk/odahuflow/sdk/models/model_route.py
> +        Default routes cannot be deleted by  They are managed by system One ModelDeployment as exactly one default route that give 100% traffic to the model  # noqa: E501
```suggestion
        Default routes cannot be deleted by user. They are managed by system
        One ModelDeployment has exactly one default Route that gives 100% traffic to the model
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/sdk/odahuflow/sdk/models/model_route.py
> +        Default routes cannot be deleted by  They are managed by system One ModelDeployment as exactly one default route that give 100% traffic to the model  # noqa: E501
```suggestion
        Default routes cannot be deleted by user. They are managed by system
        One ModelDeployment has exactly one default Route that gives 100% traffic to the model
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/operator/docs/swagger.json
> +                    "description": "Node pools to run deployments on",
```suggestion
                    "description": "Node pools to run deployments",
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/sdk/odahuflow/sdk/models/model_deployment_config.py
> +        Node pools to run deployments on  # noqa: E501
```suggestion
        Node pools to run deployments # noqa: E501
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/sdk/odahuflow/sdk/models/model_deployment_config.py
> +        Node pools to run deployments on  # noqa: E501
```suggestion
        Node pools to run deployments # noqa: E501
```

2020-11-30 11:06 UTC, BPylypenko commented on packages/sdk/odahuflow/sdk/models/model_deployment_config.py
> +        Node pools to run deployments on  # noqa: E501
I see a lot of # noqa: E501. As I found, it's for [pycodestyle](https://pycodestyle.pycqa.org/en/latest/intro.html) to ignore the line, but I couldn't find where we run/use `pycodestyle` and also we have a config file for `pydocstyle`, and I haven't found where we use this one either.

Could you, please, show where we use it?

2020-11-30 12:53 UTC, vlad-tokarev commented on packages/sdk/odahuflow/sdk/models/model_deployment_config.py
> +        Node pools to run deployments on  # noqa: E501
First, As I remember we used pydoc linter for a long time ago. Not for now.
Second, all this files are generated by swagger code-gen, and it looks like swag code-gen set this annotation

2020-11-30 13:45 UTC, BPylypenko approved these changes

2020-11-30 15:09 UTC, BPylypenko approved these changes

2020-12-01 06:47 UTC, merged