Feat/service catalog
odahu/odahu-flow pull request #457
Opened 2020-12-18 10:23 UTC by vlad-tokarev

2020-12-25 16:13 UTC, keshamin requested changes

2020-12-25 16:13 UTC, keshamin commented on packages/operator/pkg/servicecatalog/reflector.go
> +				r.eventCache.put(event.EntityID, event.Event)
As discussed in chat, this cache is only added to and never cleaned up. This may lead to a memory leak.

2021-01-11 10:31 UTC, keshamin approved these changes

2021-01-11 18:58 UTC, karbyshevds approved these changes

2021-01-12 08:54 UTC, merged