[442] readinessProbe & livenessProbe InitialDelays should start from 0
odahu/odahu-flow pull request #474
Opened 2021-01-19 12:53 UTC by BPylypenko

closes https://github.com/odahu/odahu-flow/issues/442

2021-01-20 10:17 UTC, vlad-tokarev requested changes

2021-01-20 10:17 UTC, vlad-tokarev commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
> +	MdDefaultLivenessProbeInitialDelay  = int32(0)
Why would you like to decrease default delays?

2021-01-20 11:40 UTC, BPylypenko commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
> +	MdDefaultLivenessProbeInitialDelay  = int32(0)
I just decided to set the default value of Kubernetes for this parameter:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
> initialDelaySeconds: Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.

2021-01-20 11:52 UTC, vlad-tokarev commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
> +	MdDefaultLivenessProbeInitialDelay  = int32(0)
But why?

2021-01-20 13:01 UTC, vlad-tokarev commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
> +	MdDefaultLivenessProbeInitialDelay  = int32(0)
Updated question

2021-01-20 13:43 UTC, BPylypenko commented on packages/operator/pkg/apiserver/routes/v1/deployment/model_deployment_validation.go
> +	MdDefaultLivenessProbeInitialDelay  = int32(0)
discussed on the meeting

2021-01-20 14:18 UTC, vlad-tokarev approved these changes

2021-01-26 15:23 UTC, keshamin approved these changes

2021-01-26 15:37 UTC, merged