601 fixing missing createdAT field
odahu/odahu-flow pull request #602
Opened 2021-07-15 10:59 UTC by lev-titov

2021-07-19 09:55 UTC, keshamin requested changes

2021-07-19 09:55 UTC, keshamin commented on packages/operator/pkg/repository/connection/vault/connection.go
> +		existedConn.UpdatedAt = conn.UpdatedAt
All the logic should be removed from repository. The repository is responsible for only saving an object **as is**. Any required checks and modifications should take place on Service level. 
Currently both service and repository make Get request to Vault which is unnecessary.

2021-07-21 09:32 UTC, keshamin approved these changes
I implemented the change that I myself requested, so now I approve it.

2021-07-23 11:37 UTC, BPylypenko approved these changes

2021-07-26 12:23 UTC, merged